=== HydrologicEngineeringCenter/cwms-database/schema/src/xml/Ratings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.hec.usace.army.mil/xmlSchema/cwms/ratings"
           xmlns:rt="http://www.hec.usace.army.mil/xmlSchema/cwms/ratings"
           xmlns:dt="http://www.hec.usace.army.mil/xmlSchema/cwms/hec-datatypes"
           elementFormDefault="unqualified">
  <!--
      Import the data type schema
  -->
  <xs:import namespace="http://www.hec.usace.army.mil/xmlSchema/cwms/hec-datatypes"
             schemaLocation="hec-datatypes.xsd"/>

  <!-- Text Types with Length Restrictions -->

  <xs:simpleType name="text16-type">
    <xs:restriction base="xs:string">
      <xs:maxLength value="16"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="text32-type">
    <xs:restriction base="xs:string">
      <xs:maxLength value="32"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="text256-type">
    <xs:restriction base="xs:string">
      <xs:maxLength value="256"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Rounding Specification Types -->

  <xs:simpleType name="rounding-spec-type">
    <xs:restriction base="xs:string">
      <xs:pattern value=" ?[0-9]{10} ?"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ind-rounding-spec-type">
    <xs:simpleContent>
      <xs:extension base="rt:rounding-spec-type">
        <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ind-rounding-specs-type">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="ind-rounding-spec" type="rt:ind-rounding-spec-type"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Local Boolean Type that Allows Surrounding WhiteSpace -->

  <xs:simpleType name="boolean">
    <xs:restriction base="xs:string">
      <xs:pattern value=" ?(true|false) ?"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Local Double Type that Allows Surrounding WhiteSpace -->

  <xs:simpleType name="double">
    <xs:restriction base="xs:string">
      <xs:pattern value=" ?(-?[0-9]*[.]?[0-9]*([Ee]-?[0-9]+)?|NaN|INF) ?"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Local DateTime Type that Allows Surrounding WhiteSpace -->

  <xs:simpleType name="dateTime">
    <xs:restriction base="xs:string">
      <xs:pattern value=" ?-?[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]+)?(Z|([+]|-)[0-9]{2}:[0-9]{2})? ?"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Rating Method Type -->

  <xs:simpleType name="rating-method-type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[Nn][Uu][Ll][Ll]|[Ee][Rr][Rr][Oo][Rr]|[Ll][Ii][Nn][Ee][Aa][Rr]|[Ll][Oo][Gg][Aa][Rr][Ii][Tt][Hh][Mm][Ii][Cc]|[Ll][Ii][Nn]-[Ll][Oo][Gg]|[Ll][Oo][Gg]-[Ll][Ii][Nn]|[Pp][Rr][Ee][Vv][Ii][Oo][Uu][Ss]|[Nn][Ee][Xx][Tt]|[Nn][Ee][Aa][Rr][Ee][Ss][Tt]|[Ll][Oo][Ww][Ee][Rr]|[Hh][Ii][Gg][Hh][Ee][Rr]|[Cc][Ll][Oo][Ss][Ee][Ss][Tt]"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Point Types -->

  <xs:simpleType name="note-type">
    <xs:restriction base="xs:string">
      <xs:maxLength value="16"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="point-type">
    <xs:sequence>
      <xs:element name="ind" type="xs:double"/>
      <xs:element name="dep" type="xs:double"/>
      <xs:element name="note" type="rt:note-type" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="other-ind-type">
    <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="value" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="points-type">
    <xs:sequence>
      <xs:element name="other-ind" type="rt:other-ind-type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="point" type="rt:point-type" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Parameter Spec Types -->

  <xs:complexType name="ind-parameter-spec-type">
     <xs:sequence>
      <xs:element name="parameter" type="dt:cwms-parameter-type"/>
      <xs:element name="in-range-method" type="rt:rating-method-type"/>
      <xs:element name="out-range-low-method" type="rt:rating-method-type"/>
      <xs:element name="out-range-high-method" type="rt:rating-method-type"/>
    </xs:sequence>
    <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="ind-parameter-specs-type">
    <xs:sequence>
      <xs:element name="ind-parameter-spec" type="rt:ind-parameter-spec-type" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Virtual Rating Types -->

  <xs:simpleType name="connections-type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[Rr]\d([Dd]|[Ii]\d)=([Rr]\d([Dd]|[Ii]\d)|[Ii]\d)(,[Rr]\d([Dd]|[Ii]\d)=([Rr]\d([Dd]|[Ii]\d)|[Ii]\d))*"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="source-rating-or-expression-type">
    <xs:choice>
      <xs:element name="rating-spec-id" type="dt:cwms-rating-spec-with-units-type"/>
      <xs:element name="rating-expression" type="dt:cwms-rating-expression-with-units-type"/>
    </xs:choice>
    <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="source-ratings-or-expressions-type">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="source-rating" type="rt:source-rating-or-expression-type"/>
    </xs:sequence>
  </xs:complexType>

 <!-- Transitional Rating Types -->

  <xs:simpleType name="expression-type">
    <xs:restriction base="xs:string">
      <xs:maxLength value="256"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="positional-expression-type">
    <xs:simpleContent>
      <xs:extension base="rt:expression-type">
        <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="logical-operation-type">
    <xs:sequence>
      <xs:element name="when" type="rt:expression-type"/>
      <xs:element name="then" type="rt:expression-type"/>
    </xs:sequence>
    <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="selection-type">
    <xs:sequence>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="case" type="rt:logical-operation-type"/>
      </xs:sequence>
      <xs:element name="default" type="rt:expression-type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="source-rating-type">
    <xs:simpleContent>
      <xs:extension base="dt:cwms-rating-spec-type">
        <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="source-ratings-type">
    <xs:sequence>
      <xs:element name="rating-spec-id" type="rt:source-rating-type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Rating Template (Top Level) Element -->

  <xs:element name="rating-template">
    <xs:annotation>
      <xs:documentation>
        A named collection of rating parameters and lookup behaviors.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="parameters-id" type="dt:cwms-rating-parameters-type"/>
        <xs:element name="version" type="rt:text32-type"/>
        <xs:element name="ind-parameter-specs" type="rt:ind-parameter-specs-type"/>
        <xs:element name="dep-parameter" type="dt:cwms-parameter-type"/>
        <xs:element name="description" type="rt:text256-type" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="office-id" type="rt:text16-type" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Rating Specification (Top Level) Element -->

  <xs:element name="rating-spec">
    <xs:annotation>
      <xs:documentation>
        A named collection of location, rating template, temporal lookup behaviors,
        update settings, and rounding specifications.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rating-spec-id" type="dt:cwms-rating-spec-type"/>
        <xs:element name="template-id" type="dt:cwms-rating-template-type"/>
        <xs:element name="location-id" type="dt:cwms-location-type"/>
        <xs:element name="version" type="rt:text32-type"/>
        <xs:element name="source-agency" type="rt:text32-type" minOccurs="0"/>
        <xs:element name="in-range-method" type="rt:rating-method-type"/>
        <xs:element name="out-range-low-method" type="rt:rating-method-type"/>
        <xs:element name="out-range-high-method" type="rt:rating-method-type"/>
        <xs:element name="active" type="xs:boolean"/>
        <xs:element name="auto-update" type="xs:boolean"/>
        <xs:element name="auto-activate" type="xs:boolean"/>
        <xs:element name="auto-migrate-extension" type="xs:boolean"/>
        <xs:element name="ind-rounding-specs" type="rt:ind-rounding-specs-type" maxOccurs="unbounded"/>
        <xs:element name="dep-rounding-spec" type="rt:rounding-spec-type"/>
        <xs:element name="description" type="rt:text256-type" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="office-id" type="rt:text16-type" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Simple Rating (Top Level) Element -->

  <xs:element name="simple-rating">
    <xs:annotation>
      <xs:documentation>
        A dated rating consisting of a single lookup table or a single formula with specified parameter units.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
      	<xs:element name="rating-spec-id"
      		type="dt:cwms-rating-spec-type" />
      	<xs:element name="vertical-datum-info"
      		type="dt:vertical-datum-info-type" minOccurs="0" />
      	<!-- Only if includes elev data -->
      	<xs:element name="units-id" type="dt:cwms-rating-units-type" />
      	<xs:element name="effective-date" type="xs:dateTime" />
      	<xs:element name="transition-start-date" type="xs:dateTime" minOccurs="0"/>
      	<xs:element name="create-date" type="xs:dateTime" minOccurs="0" />
      	<xs:element name="active" type="xs:boolean" />
      	<xs:element name="description" type="rt:text256-type"
      		minOccurs="0" />
      	<xs:choice>
      		<xs:element name="formula"
      			type="dt:cwms-rating-formula-type" />
      		<xs:sequence>
      			<xs:element name="rating-points" type="rt:points-type" maxOccurs="unbounded" />
      			<xs:element name="extension-points" type="rt:points-type" minOccurs="0" maxOccurs="unbounded" />
      		</xs:sequence>
      	</xs:choice>
      </xs:sequence>
      <xs:attribute name="office-id" type="rt:text16-type" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="rating" substitutionGroup="rt:simple-rating">
    <xs:annotation>
      <xs:documentation>
        An alias for simple-rating.
      </xs:documentation>
    </xs:annotation>
</xs:element>

  <!-- Virtual Rating (Top Level) Element -->

  <xs:element name="virtual-rating">
    <xs:annotation>
      <xs:documentation>
        A rating created by connecting inputs and outputs of two or more existing ratings to
        form a rating with a new parameters-id.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rating-spec-id" type="dt:cwms-rating-spec-type"/>
        <xs:element name="effective-date" type="xs:dateTime"/>
      	<xs:element name="transition-start-date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="create-date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="active" type="xs:boolean"/>
        <xs:element name="description" type="rt:text256-type" minOccurs="0"/>
        <xs:element name="connections" type="rt:connections-type"/>
        <xs:element name="source-ratings" type="rt:source-ratings-or-expressions-type"/>
      </xs:sequence>
      <xs:attribute name="office-id" type="rt:text16-type" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Transistional Rating (Top Level) Element -->

  <xs:element name="transitional-rating">
    <xs:annotation>
      <xs:documentation>
        A rating created by specifying which (or which combination) of existing ratings with
        identical parameters-ids are used based on values of the input parameters.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rating-spec-id" type="dt:cwms-rating-spec-type"/>
        <xs:element name="units-id" type="dt:cwms-rating-units-type"/>
        <xs:element name="effective-date" type="xs:dateTime"/>
      	<xs:element name="transition-start-date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="create-date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="active" type="xs:boolean"/>
        <xs:element name="description" type="rt:text256-type" minOccurs="0"/>
        <xs:element name="select" type="rt:selection-type"/>
        <xs:element name="source-ratings" type="rt:source-ratings-type"/>
      </xs:sequence>
      <xs:attribute name="office-id" type="rt:text16-type" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- USGS Stream Rating (Top Level) Element -->

  <xs:element name="usgs-stream-rating">
    <xs:complexType>
    <xs:annotation>
      <xs:documentation>
        A stage;flow rating that utilizes the USGS-style lookup interpolation
        using stage shifts and/or logarhithmic interpolation offsets.
      </xs:documentation>
    </xs:annotation>
      <xs:sequence>
        <xs:element name="rating-spec-id" type="dt:cwms-rating-spec-type"/>
        <xs:element name="vertical-datum-info" type="dt:vertical-datum-info-type" minOccurs="0"/> <!-- Only if includes elev data -->
        <xs:element name="units-id" type="dt:cwms-rating-units-type"/>
        <xs:element name="effective-date" type="xs:dateTime"/>
        <xs:element name="transition-start-date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="create-date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="active" type="xs:boolean"/>
        <xs:element name="description" type="rt:text256-type" minOccurs="0"/>
        <xs:sequence>
          <xs:element name="height-shifts" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
              	<xs:element name="effective-date" type="xs:dateTime" />
              	<xs:element name="transition-start-date" type="xs:dateTime" minOccurs="0"/>
              	<xs:element name="create-date" type="xs:dateTime"
              		minOccurs="0" />
              	<xs:element name="active" type="xs:boolean" />
              	<xs:element name="description" type="rt:text256-type"
              		minOccurs="0" />
              	<xs:element name="point" type="rt:point-type"
              		maxOccurs="unbounded" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="height-offsets" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="point" type="rt:point-type" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
      		<xs:sequence>
      			<xs:element name="rating-points" type="rt:points-type" maxOccurs="unbounded" />
      			<xs:element name="extension-points" type="rt:points-type" minOccurs="0" maxOccurs="unbounded" />
      		</xs:sequence>
        </xs:sequence>
      </xs:sequence>
      <xs:attribute name="office-id" type="rt:text16-type" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Ratings Document Element -->

  <xs:element name="ratings">
    <xs:annotation>
      <xs:documentation>
        A collection of rating templates, rating specifications, and ratings of various types.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rt:rating-template" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="rt:rating-spec" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="rt:simple-rating"/>
          <xs:element ref="rt:usgs-stream-rating"/>
          <xs:element ref="rt:virtual-rating"/>
          <xs:element ref="rt:transitional-rating"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== HydrologicEngineeringCenter/cwms-database/src/test/data/ratings/xsl_test_5-virtual_rating.xml
<ratings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://www.hec.usace.army.mil/xmlSchema/cwms/Ratings.xsd">
  <rating-template office-id="SWT">
    <parameters-id>Stage;Flow</parameters-id>
    <version>USGS-Production</version>
    <ind-parameter-specs>
      <ind-parameter-spec position="1">
        <parameter>Stage</parameter>
        <in-range-method>LINEAR</in-range-method>
        <out-range-low-method>NULL</out-range-low-method>
        <out-range-high-method>NULL</out-range-high-method>
      </ind-parameter-spec>
    </ind-parameter-specs>
    <dep-parameter>Flow</dep-parameter>
    <description>Production Stage;Flow rating using USGS ratings</description>
  </rating-template>
  <rating-spec office-id="SWT">
    <rating-spec-id>HASK.Stage;Flow.USGS-Production.USGS</rating-spec-id>
    <template-id>Stage;Flow.USGS-Production</template-id>
    <location-id>HASK</location-id>
    <version>USGS</version>
    <source-agency/>
    <in-range-method>LINEAR</in-range-method>
    <out-range-low-method>NULL</out-range-low-method>
    <out-range-high-method>PREVIOUS</out-range-high-method>
    <active>true</active>
    <auto-update>true</auto-update>
    <auto-activate>true</auto-activate>
    <auto-migrate-extension>false</auto-migrate-extension>
    <ind-rounding-specs>
      <ind-rounding-spec position="1">4444444444</ind-rounding-spec>
    </ind-rounding-specs>
    <dep-rounding-spec>4444444444</dep-rounding-spec>
    <description>HASK Production Stage;Flow rating using USGS ratings</description>
  </rating-spec>
  <virtual-rating office-id="SWT">
    <rating-spec-id>HASK.Stage;Flow.USGS-Production.USGS</rating-spec-id>
    <effective-date>2019-05-06T08:20:00Z</effective-date>
    <create-date>2020-05-13T12:24:34Z</create-date>
    <active>true</active>
    <description/>
    <connections>R2I1=I1,R2I2=R1D,R3I1=R2D</connections>
    <source-ratings>
      <source-rating position="1">
        <rating-spec-id>HASK.Stage;Stage-Correction.USGS-CORR.USGS {ft;ft}</rating-spec-id>
      </source-rating>
      <source-rating position="2">
        <rating-expression>I1 + I2 {ft,ft;ft}</rating-expression>
      </source-rating>
      <source-rating position="3">
        <rating-spec-id>HASK.Stage;Flow.USGS-BASE.USGS {ft;cfs}</rating-spec-id>
      </source-rating>
    </source-ratings>
  </virtual-rating>
</ratings>

=== HydrologicEngineeringCenter/cwms-database/src/test/data/ratings/xsl_test_2-one_ind_param_simple_rating.xml
<ratings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://www.hec.usace.army.mil/xmlSchema/cwms/Ratings.xsd">
  <rating-template office-id="XXX">
    <parameters-id>Elev;Stor</parameters-id>
    <version>Linear</version>
    <ind-parameter-specs>
      <ind-parameter-spec position="1">
        <parameter>Elev</parameter>
        <in-range-method>LINEAR</in-range-method>
        <out-range-low-method>NEAREST</out-range-low-method>
        <out-range-high-method>NEAREST</out-range-high-method>
      </ind-parameter-spec>
    </ind-parameter-specs>
    <dep-parameter>Stor</dep-parameter>
    <description/>
  </rating-template>
  <rating-spec office-id="XXX">
    <rating-spec-id>HEYB.Elev;Stor.Linear.Production</rating-spec-id>
    <template-id>Elev;Stor.Linear</template-id>
    <location-id>HEYB</location-id>
    <version>Production</version>
    <source-agency/>
    <in-range-method>PREVIOUS</in-range-method>
    <out-range-low-method>NEAREST</out-range-low-method>
    <out-range-high-method>PREVIOUS</out-range-high-method>
    <active>true</active>
    <auto-update>false</auto-update>
    <auto-activate>false</auto-activate>
    <auto-migrate-extension>false</auto-migrate-extension>
    <ind-rounding-specs>
      <ind-rounding-spec position="1">4444444444</ind-rounding-spec>
    </ind-rounding-specs>
    <dep-rounding-spec>4444444444</dep-rounding-spec>
    <description>Heyburn Lake Reservoir Storage Capacity Production Rating</description>
  </rating-spec>
  <simple-rating office-id="XXX">
    <rating-spec-id>HEYB.Elev;Stor.Linear.Production</rating-spec-id>
    <vertical-datum-info unit="ft">
      <native-datum>NGVD-29</native-datum>
      <elevation>0</elevation>
      <offset estimate="true">
        <to-datum>NAVD-88</to-datum>
        <value>0.3678</value>
      </offset>
    </vertical-datum-info>
    <units-id vertical-datum="">ft;ac-ft</units-id>
    <effective-date>2015-05-21T19:42:00Z</effective-date>
    <create-date>2012-11-06T17:08:00Z</create-date>
    <active>true</active>
    <description/>
    <rating-points>
      <point>
        <ind>732</ind>
        <dep>0</dep>
      </point>
      <point>
        <ind>732.5</ind>
        <dep>1</dep>
      </point>
      <point>
        <ind>733</ind>
        <dep>2</dep>
      </point>
      <point>
        <ind>733.5</ind>
        <dep>3.5</dep>
      </point>
      <point>
        <ind>734</ind>
        <dep>5</dep>
      </point>
      <point>
        <ind>734.5</ind>
        <dep>7.5</dep>
      </point>
      <point>
        <ind>735</ind>
        <dep>10</dep>
      </point>
      <point>
        <ind>735.5</ind>
        <dep>14.5</dep>
      </point>
      <point>
        <ind>736</ind>
        <dep>19</dep>
      </point>
      <point>
        <ind>736.5</ind>
        <dep>25.5</dep>
      </point>
      <point>
        <ind>737</ind>
        <dep>32</dep>
      </point>
      <point>
        <ind>737.5</ind>
        <dep>41</dep>
      </point>
      <point>
        <ind>738</ind>
        <dep>50</dep>
      </point>
      <point>
        <ind>738.5</ind>
        <dep>62</dep>
      </point>
      <point>
        <ind>739</ind>
        <dep>74</dep>
      </point>
      <point>
        <ind>739.5</ind>
        <dep>89</dep>
      </point>
      <point>
        <ind>740</ind>
        <dep>104</dep>
      </point>
      <point>
        <ind>740.5</ind>
        <dep>123</dep>
      </point>
      <point>
        <ind>741</ind>
        <dep>142</dep>
      </point>
      <point>
        <ind>741.5</ind>
        <dep>165</dep>
      </point>
      <point>
        <ind>742</ind>
        <dep>188</dep>
      </point>
      <point>
        <ind>742.5</ind>
        <dep>217.5</dep>
      </point>
      <point>
        <ind>743</ind>
        <dep>247</dep>
      </point>
      <point>
        <ind>743.5</ind>
        <dep>282.5</dep>
      </point>
      <point>
        <ind>744</ind>
        <dep>318</dep>
      </point>
      <point>
        <ind>744.5</ind>
        <dep>360.5</dep>
      </point>
      <point>
        <ind>745</ind>
        <dep>403</dep>
      </point>
      <point>
        <ind>745.5</ind>
        <dep>452.5</dep>
      </point>
      <point>
        <ind>746</ind>
        <dep>502</dep>
      </point>
      <point>
        <ind>746.5</ind>
        <dep>560</dep>
      </point>
      <point>
        <ind>747</ind>
        <dep>618</dep>
      </point>
      <point>
        <ind>747.5</ind>
        <dep>684.5</dep>
      </point>
      <point>
        <ind>747.75</ind>
        <dep>717.75</dep>
      </point>
      <point>
        <ind>748</ind>
        <dep>751</dep>
      </point>
      <point>
        <ind>748.5</ind>
        <dep>827.5</dep>
      </point>
      <point>
        <ind>749</ind>
        <dep>904</dep>
      </point>
      <point>
        <ind>749.5</ind>
        <dep>990</dep>
      </point>
      <point>
        <ind>750</ind>
        <dep>1076</dep>
      </point>
      <point>
        <ind>750.5</ind>
        <dep>1174</dep>
      </point>
      <point>
        <ind>751</ind>
        <dep>1272</dep>
      </point>
      <point>
        <ind>751.5</ind>
        <dep>1384.5</dep>
      </point>
      <point>
        <ind>752</ind>
        <dep>1497</dep>
      </point>
      <point>
        <ind>752.5</ind>
        <dep>1627</dep>
      </point>
      <point>
        <ind>753</ind>
        <dep>1757</dep>
      </point>
      <point>
        <ind>753.5</ind>
        <dep>1904</dep>
      </point>
      <point>
        <ind>754</ind>
        <dep>2051</dep>
      </point>
      <point>
        <ind>754.5</ind>
        <dep>2104.5</dep>
      </point>
      <point>
        <ind>755</ind>
        <dep>2380</dep>
      </point>
      <point>
        <ind>756</ind>
        <dep>2748</dep>
      </point>
      <point>
        <ind>757</ind>
        <dep>3150</dep>
      </point>
      <point>
        <ind>758</ind>
        <dep>3584</dep>
      </point>
      <point>
        <ind>759</ind>
        <dep>4059</dep>
      </point>
      <point>
        <ind>760</ind>
        <dep>4584</dep>
      </point>
      <point>
        <ind>761</ind>
        <dep>5161</dep>
      </point>
      <point>
        <ind>762</ind>
        <dep>5855</dep>
      </point>
      <point>
        <ind>763</ind>
        <dep>6703</dep>
      </point>
      <point>
        <ind>764</ind>
        <dep>7678</dep>
      </point>
      <point>
        <ind>765</ind>
        <dep>8778</dep>
      </point>
      <point>
        <ind>766</ind>
        <dep>10005</dep>
      </point>
      <point>
        <ind>767</ind>
        <dep>11358</dep>
      </point>
      <point>
        <ind>768</ind>
        <dep>12837</dep>
      </point>
      <point>
        <ind>769</ind>
        <dep>14442</dep>
      </point>
      <point>
        <ind>770</ind>
        <dep>16174</dep>
      </point>
      <point>
        <ind>771</ind>
        <dep>18031</dep>
      </point>
      <point>
        <ind>772</ind>
        <dep>20014</dep>
      </point>
      <point>
        <ind>773</ind>
        <dep>22124</dep>
      </point>
      <point>
        <ind>774</ind>
        <dep>24359</dep>
      </point>
      <point>
        <ind>775</ind>
        <dep>26721</dep>
      </point>
      <point>
        <ind>776</ind>
        <dep>29221</dep>
      </point>
      <point>
        <ind>777</ind>
        <dep>31872</dep>
      </point>
      <point>
        <ind>778</ind>
        <dep>34674</dep>
      </point>
      <point>
        <ind>779</ind>
        <dep>37626</dep>
      </point>
      <point>
        <ind>780</ind>
        <dep>40730</dep>
      </point>
      <point>
        <ind>781</ind>
        <dep>43984</dep>
      </point>
      <point>
        <ind>782</ind>
        <dep>47389</dep>
      </point>
      <point>
        <ind>783</ind>
        <dep>50945</dep>
      </point>
      <point>
        <ind>784</ind>
        <dep>54652</dep>
      </point>
      <point>
        <ind>785</ind>
        <dep>58510</dep>
      </point>
      <point>
        <ind>786</ind>
        <dep>62518</dep>
      </point>
      <point>
        <ind>787</ind>
        <dep>66678</dep>
      </point>
      <point>
        <ind>788</ind>
        <dep>70988</dep>
      </point>
      <point>
        <ind>789</ind>
        <dep>75449</dep>
      </point>
      <point>
        <ind>790</ind>
        <dep>80061</dep>
      </point>
      <point>
        <ind>791</ind>
        <dep>84823</dep>
      </point>
      <point>
        <ind>792</ind>
        <dep>89737</dep>
      </point>
      <point>
        <ind>793</ind>
        <dep>94801</dep>
      </point>
      <point>
        <ind>794</ind>
        <dep>100017</dep>
      </point>
      <point>
        <ind>795</ind>
        <dep>105383</dep>
      </point>
      <point>
        <ind>796</ind>
        <dep>110900</dep>
      </point>
      <point>
        <ind>797</ind>
        <dep>116567</dep>
      </point>
      <point>
        <ind>798</ind>
        <dep>122386</dep>
      </point>
      <point>
        <ind>799</ind>
        <dep>128355</dep>
      </point>
      <point>
        <ind>800</ind>
        <dep>134476</dep>
      </point>
      <point>
        <ind>801</ind>
        <dep>140747</dep>
      </point>
      <point>
        <ind>802</ind>
        <dep>147169</dep>
      </point>
      <point>
        <ind>803</ind>
        <dep>153741</dep>
      </point>
      <point>
        <ind>804</ind>
        <dep>160465</dep>
      </point>
      <point>
        <ind>805</ind>
        <dep>167340</dep>
      </point>
    </rating-points>
  </simple-rating>
</ratings>
